name: "Push After Run"
description: "Push changes after a step run."
inputs:
  commit_message:
    description: "Commit message"
    required: true
  commit_detail:
    description: "Secondary Commit message"
    required: false
    default: ""
  run:
    description: "Command to run"
    required: false
    default: ":"
  head:
    description: "The branch to push to"
    required: false
    default: ${{ github.head_ref }}
  token:
    description: "The token to use for pushing"
    required: false
    default: ${{ github.token }}
  user_name:
    description: "The user name to use for pushing"
    required: false
    default: "Github Actions"
  user_email:
    description: "The user email to use for pushing"
    required: false
    default: "actions@github.com"
  author:
    description: "The author to use for pushing"
    required: false
    default: ${{github.actor}} <${{github.actor }}@users.noreply.github.com>
outputs:
  sha:
    description: "The SHA of the pushed commit. Empty if nothing was pushed."
  changes_pushed:
    description: "Boolean indicating if changes were pushed."
runs:
  using: "docker"
  image: "Dockerfile"
