name: "Push After Run"
description: "Push changes after a step run."
inputs:
  message:
    description: "Commit message"
    required: true
  message_detail:
    description: "Secondary Commit message"
    required: false
    default: ""
  run:
    description: "Command to run"
    required: false
    default: ":"
  head:
    description: "The branch to push to"
    required: false
    default: "HEAD"
  token:
    description: "The token to use for pushing"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
